var downloads =
    // 20180129113938
    // http://58.9.99.60/download/findAll

    [{
            id: 927972,
            name: "คู่มือการใช้งาน Finger Access Control 280",
            detail: "คู่มือ Fingerprint",
            description: "คู่มือการใช้งาน Finger Access Control 280",
            download_type_id: 5,
            photo: "KH-280.png",
            path: "คู่มือการใช้งาน Standalone Access Control CMG 280.pdf",
            admin: "ผู้ดูแลระบบ",
            created: "2017-11-08T09:44:27.000Z",
            dt_name: "คู่มือ Fingerprint"
        },
        {
            id: 381522,
            name: "โปรแกรม CMS Client (Win) สำหรับ IP CAMERA รองรับ NVR WIFI",
            detail: "โปรแกรม/SoftWare Installation",
            description: "โปรแกรม CMS Client สำหรับ IP CAMERA รองรับ NVR WIFI ใช้สำหรับจัดการหรือดูภาพจาก CCTV ระยะไกลผ่านโปรแกรม Client",
            download_type_id: 3,
            photo: "8_diq1.jpg",
            path: "CMS(Win).zip",
            admin: "ผู้ดูแลระบบ",
            created: "2017-07-20T02:55:24.000Z",
            dt_name: "โปรแกรม CCTV"
        },
        {
            id: 285371,
            name: "คู่มือการ backup วีดีโอออกจา AHD DVR",
            detail: "คู่มือการใช้งาน/UserManuals",
            description: "คู่มือการ backup วีดีโอออกจา AHD DVR",
            download_type_id: 1,
            photo: "DVR-to-FTP.jpg",
            path: "AHD_BackUp.pdf",
            admin: "ผู้ดูแลระบบ",
            created: "2017-09-06T04:59:31.000Z",
            dt_name: "คู่มือการใช้งาน CCTV"
        },
        {
            id: 163557,
            name: "โปรแกรม iCMS (Mac) สำหรับ IP CAMERA รองรับ NVR WIFI",
            detail: "โปรแกรม/SoftWare Installation",
            description: "โปรแกรม iCMS (Mac) สำหรับ IP CAMERA เพื่อดูภาพย้อนหลัง backup ข้อมูลต่าง ระยะไกลได้",
            download_type_id: 3,
            photo: "8_diq2.jpg",
            path: "iCMS_v1.26.04.zip",
            admin: "ผู้ดูแลระบบ",
            created: "2017-07-20T02:59:29.000Z",
            dt_name: "โปรแกรม CCTV"
        },
        {
            id: 59,
            name: "โปรแกรมนาฬิกายาม HUA ภาษาไทย ปรับปรุงใหม่ Font ใหญ่",
            detail: "โปรแกรม Fingerprint",
            description: "โปรแกรมนาฬิกายาม HUA ภาษาไทย ปรับปรุงใหม่ Font ใหญ่",
            download_type_id: 4,
            photo: "-",
            path: "setup(THA).rar",
            admin: "ผู้ดูแลระบบ",
            created: "2016-09-11T17:00:00.000Z",
            dt_name: "โปรแกรม Fingerprint"
        },
        {
            id: 58,
            name: "โปรแกรมเครื่องสแกนลายนิ้วมือ C100S จอสี",
            detail: "โปรแกรม Fingerprint",
            description: "โปรแกรมเครื่องสแกนลายนิ้วมือ C100S จอสี",
            download_type_id: 4,
            photo: "-",
            path: "C100S_Win.zip",
            admin: "ผู้ดูแลระบบ",
            created: "2016-09-11T17:00:00.000Z",
            dt_name: "โปรแกรม Fingerprint"
        },
        {
            id: 57,
            name: "วีดีโอแนนะการใช้งานระบบ Smart Home Automation Zigbee",
            detail: "วีดีโอสอนการใช้งาน",
            description: "วีดีโอแนนะการใช้งานระบบ Smart Home Automation Zigbee",
            download_type_id: 6,
            photo: "-",
            path: "https://www.youtube.com/embed/8CFir9GG31Q",
            admin: "ผู้ดูแลระบบ",
            created: "2016-09-11T17:00:00.000Z",
            dt_name: "วีดีโอสอนการใช้งาน"
        },
        {
            id: 56,
            name: "วีดีโอสอนการใช้งาน เปิด function Anti passback ระบบ Access Control + WG26bit",
            detail: "วีดีโอสอนการใช้งาน",
            description: "วีดีโอสอนการใช้งาน เปิด function Anti passback ระบบ Access Control + WG26bit",
            download_type_id: 6,
            photo: "-",
            path: "https://www.youtube.com/embed/DOchJapn0U4",
            admin: "ผู้ดูแลระบบ",
            created: "2016-09-11T17:00:00.000Z",
            dt_name: "วีดีโอสอนการใช้งาน"
        },
        {
            id: 55,
            name: "สาธิตการใช้งานระบบไม้กั้น carpark systems auto door",
            detail: "วีดีโอสอนการใช้งาน",
            description: "สาธิตการใช้งานระบบไม้กั้น carpark systems auto door",
            download_type_id: 6,
            photo: "-",
            path: "https://www.youtube.com/embed/Ei8wtgXg4Lg",
            admin: "แอดมิน",
            created: "2016-06-21T17:00:00.000Z",
            dt_name: "วีดีโอสอนการใช้งาน"
        },
        {
            id: 54,
            name: "ตัวแก้ attcheckin_thai.zip [ภาษาไทย]",
            detail: "คู่มือ Fingerprint",
            description: "attcheckin_thai เป็นตัวแก้ไขโปรแกรม attendance management ให้เป็นภาษาไทย\r\nสามารถ copy ไปวางเพื่ออัพเดทภาษาไทย ได้เลย",
            download_type_id: 5,
            photo: "-",
            path: "attcheckin_thai.zip",
            admin: "แอดมิน",
            created: "2016-06-21T17:00:00.000Z",
            dt_name: "คู่มือ Fingerprint"
        },
        {
            id: 53,
            name: "Driver USB For Power LED",
            detail: "โปรแกรม LED Display Full Color & ป้ายไฟวิ่ง Single & Dual Color",
            description: "Driver USB สำหรับ LED ป้ายไฟวิ่ง ทั้ง Single Color และ Dual Color",
            download_type_id: 7,
            photo: "-",
            path: "UsbDriver_CH341.zip",
            admin: "แอดมิน",
            created: "2016-06-13T17:00:00.000Z",
            dt_name: "โปรแกรม LED Display Full Color & ป้ายไฟวิ่ง Single & Dual Color"
        },
        {
            id: 52,
            name: "โปรแกรม Power LED 2.8.4",
            detail: "โปรแกรม LED Display Full Color & ป้ายไฟวิ่ง Single & Dual Color",
            description: "โปรแกรมบริกหารและจัดการ LED ไฟวิ่งทั้ง Single Color & Dual Coolor",
            download_type_id: 7,
            photo: "-",
            path: "PowerLed_2.84.1.zip",
            admin: "แอดมิน",
            created: "2016-06-13T17:00:00.000Z",
            dt_name: "โปรแกรม LED Display Full Color & ป้ายไฟวิ่ง Single & Dual Color"
        },
        {
            id: 51,
            name: "โปรแกรม Power LED 2.77.2",
            detail: "โปรแกรม LED Display Full Color & ป้ายไฟวิ่ง Single & Dual Color",
            description: "โปรแกรมบริกหารและจัดการ LED ไฟวิ่งทั้ง Single Color & Dual Coolor",
            download_type_id: 7,
            photo: "-",
            path: "PowerLed_2.77.2.zip",
            admin: "แอดมิน",
            created: "2016-06-13T17:00:00.000Z",
            dt_name: "โปรแกรม LED Display Full Color & ป้ายไฟวิ่ง Single & Dual Color"
        },
        {
            id: 50,
            name: "ทดสอบ LED P5 INDOOR @pattaya city ",
            detail: "วีดีโอสอนการใช้งาน",
            description: "ทดสอบ LED P5 INDOOR @pattaya city  หลังการติดตั้ง คุณภาพระดับ Full HD 1080P",
            download_type_id: 6,
            photo: "-",
            path: "https://www.youtube.com/embed/Dzg6d19vSl8",
            admin: "แอดมิน",
            created: "2016-06-13T17:00:00.000Z",
            dt_name: "วีดีโอสอนการใช้งาน"
        },
        {
            id: 49,
            name: "Training LED P5 INDOOR @pattaya city ",
            detail: "วีดีโอสอนการใช้งาน",
            description: "สอนการใช้งาน LED P5 INDOOR @pattaya city คุณภาพระดับ Full HD 1080P",
            download_type_id: 6,
            photo: "-",
            path: "https://www.youtube.com/embed/3Wt4u8tmT5U",
            admin: "แอดมิน",
            created: "2016-06-13T17:00:00.000Z",
            dt_name: "วีดีโอสอนการใช้งาน"
        },
        {
            id: 48,
            name: "คู่มือการใช้งาน iClock 680 ฉบับเต็ม (Eng)",
            detail: "คู่มือ Fingerprint",
            description: "คู่มือการใช้งาน iClock 680 ฉบับเต็ม (Eng)\r\nสอนการใช้งาน การใช้โปรแกรม iClock Autometic Data Server ตั้งแต่เริ่มต้นจนจบการใช้งาน",
            download_type_id: 5,
            photo: "-",
            path: "adms-en.pdf",
            admin: "ผู้ดูแลระบบ",
            created: "2016-03-24T17:00:00.000Z",
            dt_name: "คู่มือ Fingerprint"
        },
        {
            id: 47,
            name: "คู่มือการตั้งค่า iClock 680 ภาษาไทย",
            detail: "คู่มือ Fingerprint",
            description: "คู่มือการตั้งค่า iClock 680 ภาษาไทย\r\nสอนการตั้งค่า ADMS และ APN ผ่านเครือข่าย 3G\r\nตลอดจนการ Forward Port บน Router และการสมัครใช้บริการ DDNS เพื่อใช้งาน",
            download_type_id: 5,
            photo: "-",
            path: "UserManuals_iClock680-3G_update_2016-03-25.pdf",
            admin: "ผู้ดูแลระบบ",
            created: "2016-03-24T17:00:00.000Z",
            dt_name: "คู่มือ Fingerprint"
        },
        {
            id: 46,
            name: "คู่มือการใช้งาน โปรแกรม Time Attendance (ภาษาไทย) V4.8",
            detail: "คู่มือ Fingerprint",
            description: "คู่มือการใช้งาน โปรแกรม Time Attendance (ภาษาไทย) V4.8 แนะนำการใช้งานจัดการเครื่องสแกนลายนิ้วมือ ตลอดจนการดึงข้อมูลการบันทึกเวลา ออกรายงาน",
            download_type_id: 5,
            photo: "-",
            path: "UserManuals_Time Attendance.pdf",
            admin: "ผู้ดูแลระบบ",
            created: "2016-03-22T17:00:00.000Z",
            dt_name: "คู่มือ Fingerprint"
        },
        {
            id: 45,
            name: "ดูกล้องวงจรปิดผ่าน N_eye app",
            detail: "วีดีโอสอนการใช้งาน",
            description: "ดูกล้องวงจรปิดผ่าน N_eye app รองรับ iphone android tablet ipad\r\nสอบถามรายละเอียดเพิ่มเติมได้ที่ www.kohan.co.th",
            download_type_id: 6,
            photo: "-",
            path: "https://www.youtube.com/embed/MYZb3VLC5Sg",
            admin: "ผู้ดูแลระบบ",
            created: "2016-02-09T17:00:00.000Z",
            dt_name: "วีดีโอสอนการใช้งาน"
        },
        {
            id: 43,
            name: "ดูภาพจากกล้องผ่าน Xmeye IPHONE",
            detail: "วีดีโอสอนการใช้งาน",
            description: "ดูกล้องวงจรปิดผ่าน emeye app รองรับ iphone android tablet ipad\r\nสอบถามรายละเอียดเพิ่มเติมได้ที่ www.kohan.co.th",
            download_type_id: 6,
            photo: "-",
            path: "https://www.youtube.com/embed/SXfugBT4P3s",
            admin: "ผู้ดูแลระบบ",
            created: "2016-02-09T17:00:00.000Z",
            dt_name: "วีดีโอสอนการใช้งาน"
        },
        {
            id: 42,
            name: "โปรแกรมนาฬิกายาม รุ่นใหม่ Guard-Tour-HUA-Eng",
            detail: "โปรแกรม Fingerprint",
            description: "โปรแกรม Patrol V2 ใหม่ล่าสุด ใช้งานง่าย รองรับภาษาไทย 100% รองรับ Windows8",
            download_type_id: 4,
            photo: "-",
            path: "Guard-Tour-HUA-Eng.zip",
            admin: "ผู้ดูแลระบบ",
            created: "2016-02-04T17:00:00.000Z",
            dt_name: "โปรแกรม Fingerprint"
        },
        {
            id: 41,
            name: "โปรแกรม HD Smart PSS ForMacOsx Cloud/P2P",
            detail: "โปรแกรม/SoftWare Installation",
            description: "โปรแกรม HD Smart PSS ForMacOsx Cloud/P2P สามารถดูภาพสดจากกล้อง Dahua สำหรับเครื่อง OSX รองรับการเชื่อมต่อผ่าน SN/P2P/IP DOMAIN",
            download_type_id: 3,
            photo: "-",
            path: "DH_SmartPSS_Eng_Mac_IS_V1.11.1.R.20150114.tar",
            admin: "ผู้ดูแลระบบ",
            created: "2015-12-15T17:00:00.000Z",
            dt_name: "โปรแกรม CCTV"
        },
        {
            id: 40,
            name: "วีดีโอสอนการสมัคร NO-IP เพื่อดูกล้องออนไลน์",
            detail: "วีดีโอสอนการใช้งาน",
            description: "วีดีโอสอนการสมัคร NO-IP เพื่อดูกล้องออนไลน์",
            download_type_id: 6,
            photo: "-",
            path: "https://www.youtube.com/embed/pK-EpanU0QM",
            admin: "ผู้ดูแลระบบ",
            created: "2015-11-12T17:00:00.000Z",
            dt_name: "วีดีโอสอนการใช้งาน"
        },
        {
            id: 39,
            name: "วีดีโอเทรนนิ่ง LED P5 Indoor",
            detail: "วีดีโอสอนการใช้งาน",
            description: "วีดีโอเทรนนิ่ง LED P5 Indoor",
            download_type_id: 6,
            photo: "-",
            path: "https://www.youtube.com/embed/S4QX8Lq5lRk",
            admin: "ผู้ดูแลระบบ",
            created: "2015-11-11T17:00:00.000Z",
            dt_name: "วีดีโอสอนการใช้งาน"
        },
        {
            id: 38,
            name: "วีดีโอสาธิติการผลิต จอรับภาพ LED จากโรงงาน",
            detail: "วีดีโอสอนการใช้งาน",
            description: "วีดีโอสาธิติการผลิต จอรับภาพ LED จากโรงงาน",
            download_type_id: 6,
            photo: "-",
            path: "https://www.youtube.com/embed/8rjwh-U6Lwg",
            admin: "ผู้ดูแลระบบ",
            created: "2015-11-11T17:00:00.000Z",
            dt_name: "วีดีโอสอนการใช้งาน"
        },
        {
            id: 37,
            name: "คู่มือการเซ็ทอัพผ่าน DahuaDDNS Fee Host",
            detail: "คู่มือการใช้งาน/UserManuals",
            description: "คู่มือการเซ็ทอัพผ่าน DahuaDDNS Fee Host สำหรับเครื่องบันทึก Dahua DVR",
            download_type_id: 1,
            photo: "-",
            path: "setup-Dahua-DVR-DahuaDDNS.pdf",
            admin: "ผู้ดูแลระบบ",
            created: "2015-10-29T17:00:00.000Z",
            dt_name: "คู่มือการใช้งาน CCTV"
        },
        {
            id: 36,
            name: "การเซ็ตให้กล้องเชื่อมต่อแบบ P2P สำหรับ Dahua DVR",
            detail: "คู่มือการใช้งาน/UserManuals",
            description: "การเซ็ตให้กล้องเชื่อมต่อแบบ P2P สำหรับ Dahua DVR",
            download_type_id: 1,
            photo: "-",
            path: "Dahua-DVR-P2P.pdf",
            admin: "ผู้ดูแลระบบ",
            created: "2015-10-29T17:00:00.000Z",
            dt_name: "คู่มือการใช้งาน CCTV"
        },
        {
            id: 35,
            name: "คู่มือการตั้งค่าดูกล้องแบบ IP/Domain ของ Dahua DVR ผ่าน SmartPSS",
            detail: "คู่มือการใช้งาน/UserManuals",
            description: "คู่มือการตั้งค่าดูกล้องแบบ IP/Domain ของ Dahua DVR ผ่าน SmartPSS",
            download_type_id: 1,
            photo: "-",
            path: "Setting-DahuaDVR-IP-Domain.pdf",
            admin: "ผู้ดูแลระบบ",
            created: "2015-10-29T17:00:00.000Z",
            dt_name: "คู่มือการใช้งาน CCTV"
        },
        {
            id: 34,
            name: "คู่มือการติดตั้งโปรแกรม SmartPSS สำหรับ Dahua DVR",
            detail: "คู่มือการใช้งาน/UserManuals",
            description: "คู่มือการติดตั้งโปรแกรม SmartPSS สำหรับ Dahua DVR รองรับทั้ง DDNS P2P DahuaDDNS",
            download_type_id: 1,
            photo: "-",
            path: "SmartPSS-setup.pdf",
            admin: "ผู้ดูแลระบบ",
            created: "2015-10-29T17:00:00.000Z",
            dt_name: "คู่มือการใช้งาน CCTV"
        },
        {
            id: 33,
            name: "คู่มือการติดตั้งโปรแกรม SmartPSS",
            detail: "คู่มือการใช้งาน/UserManuals",
            description: "คู่มือการติดตั้งโปรแกรม SmartPSS เพื่อดูภาพจากกล้อง Dahua DVR",
            download_type_id: 1,
            photo: "-",
            path: "Install-SmartPSS.pdf",
            admin: "ผู้ดูแลระบบ",
            created: "2015-10-29T17:00:00.000Z",
            dt_name: "คู่มือการใช้งาน CCTV"
        },
        {
            id: 32,
            name: "โปรแกรม Smart PSS สำหรับ DahuaDVR สำหรับ Windows",
            detail: "โปรแกรม/SoftWare Installation",
            description: "โปรแกรม Smart PSS สำหรับ DahuaDVR สำหรับ Windows เพื่อใช้ดูกล้องวงจรปิดของ Dahua สามารถรองรับทั้ง IP/DOMAIN P2P DahuaDDNS",
            download_type_id: 3,
            photo: "-",
            path: "DH_Smart-PSS_Eng.zip",
            admin: "ผู้ดูแลระบบ",
            created: "2015-10-29T17:00:00.000Z",
            dt_name: "โปรแกรม CCTV"
        },
        {
            id: 31,
            name: "คู่มือการใช้งานนาฬิกายาม GT4,GT/1",
            detail: "คู่มือ Fingerprint",
            description: "คู่มือการใช้งานนาฬิกายาม GT4,GT/1",
            download_type_id: 5,
            photo: "-",
            path: "GT4_Manuals.pdf",
            admin: "ผู้ดูแลระบบ",
            created: "2015-09-10T21:26:08.000Z",
            dt_name: "คู่มือ Fingerprint"
        },
        {
            id: 30,
            name: "โปรแกรม Patrol Management Systems",
            detail: "โปรแกรม Fingerprint",
            description: "โปรแกรม Patrol Management Systems เป็นโปรแกรมใช้บริหารจัดการ นาฬิกายาม",
            download_type_id: 4,
            photo: "-",
            path: "GT4.zip",
            admin: "ผู้ดูแลระบบ",
            created: "2015-09-10T19:24:11.000Z",
            dt_name: "โปรแกรม Fingerprint"
        },
        {
            id: 29,
            name: "โปรแกรม Attentdance Management Systems",
            detail: "โปรแกรม Fingerprint",
            description: "โปรแกรม Attentdance Management Systems เป็นโปรแกรมสำหรับบริหารและจัดการเครื่องสแกนลายนิ้วมือ สำหรับเครื่อง C100,F7,F707,F708,U300C,F8,F18",
            download_type_id: 4,
            photo: "-",
            path: "Fingerprint.zip",
            admin: "ผู้ดุแลระบบ",
            created: "2015-09-10T19:24:13.000Z",
            dt_name: "โปรแกรม Fingerprint"
        },
        {
            id: 28,
            name: "โปรแกรม PSS For Dahua Windows",
            detail: "โปรแกรม/SoftWare Installation",
            description: "โปรแกรม PSS For Dahua สำหรับ Windows ใช้ในการดูกล้อง CCTV ผ่าน Desktop เหมาะสำหรับ Dahua DVR",
            download_type_id: 3,
            photo: "-",
            path: "PSS_V4060.rar",
            admin: "ผู้ดูแลระบบ",
            created: "2015-09-10T20:34:17.000Z",
            dt_name: "โปรแกรม CCTV"
        },
        {
            id: 27,
            name: "โปรแกรม iVMS 4200 สำหรับ Windows",
            detail: "โปรแกรม/SoftWare Installation",
            description: "โปรแกรม iVMS 4200 สำหรับ Windows เป็นโปรแกรมที่ใช้ดูกล้องวงจรปิด ",
            download_type_id: 3,
            photo: "-",
            path: "iVMS-4200(v2.02.03.03).zip",
            admin: "ผู้ดูแลระบบ",
            created: "2015-09-10T19:08:09.000Z",
            dt_name: "โปรแกรม CCTV"
        },
        {
            id: 26,
            name: "โปรแกรม CMS แบบ P2P สำหรับ Windows",
            detail: "โปรแกรม/SoftWare Installation",
            description: "โปรแกรม CMS สำหรับดูกล้องวงจรปิด รองรับ DVR Sinovision,TopView,HIP และอื่นๆอีกมากมาย",
            download_type_id: 3,
            photo: "-",
            path: "CMS_Wins.zip",
            admin: "ผู้ดุแลระบบ",
            created: "2015-09-10T20:08:05.000Z",
            dt_name: "โปรแกรม CCTV"
        },
        {
            id: 25,
            name: "การดูกล้องผ่าน Firefox & Quicktime Plugins",
            detail: "คู่มือการใช้งาน/UserManuals",
            description: "การดูกล้องผ่าน Firefox & Quicktime Plugins",
            download_type_id: 1,
            photo: "-",
            path: "CCTV_firefox_Usermanuls.pdf",
            admin: "ผู้ดูแลระบบ",
            created: "2015-09-06T19:24:11.000Z",
            dt_name: "คู่มือการใช้งาน CCTV"
        },
        {
            id: 24,
            name: "โปรแกรม vMeyeSuper For Mac",
            detail: "โปรแกรม/SoftWare Installation",
            description: "โปรแกรม vMeyeSuper For Mac เป็นโปรแกรมดูกล้องวงจรปิด ค่าย Sinovision กล้องที่ใช้ vMeyeSuper,vMeyeClond,vMeyeClond Lite\r\n สามารถใช้โปรแกรม vMeyeSuper บน Mac เพื่อดูกล้องวงจรปิดได้\r\n",
            download_type_id: 3,
            photo: "-",
            path: "vMEyeSuper.zip",
            admin: "ผู้ดูแลระบบ",
            created: "2015-09-04T20:36:22.000Z",
            dt_name: "โปรแกรม CCTV"
        },
        {
            id: 23,
            name: "โปรแกรม PSSMini สำหรับ  Apple OSX",
            detail: "โปรแกรม/SoftWare Installation",
            description: "โปรแกรม PSSMini สำหรับ  Apple OSX เป็นโปรแกรมแกรมที่ใช้ดู CCTV ผ่านเครื่อง Mac รองรับ Dahua DVR",
            download_type_id: 3,
            photo: "-",
            path: "General_PSS_Eng_MAC.zip",
            admin: "ผู้ดูแลระบบ",
            created: "2015-09-04T19:20:11.000Z",
            dt_name: "โปรแกรม CCTV"
        },
        {
            id: 22,
            name: "โปรแกรม iVMS-4200 Mac ดูกล้องผ่าน OSX",
            detail: "โปรแกรม/SoftWare Installation",
            description: "โปรแกรม iVMS-4200 Mac ดูกล้องผ่าน OSX สามารถดูกล้อง CCTV ผ่านทางเครื่อง Apple ได้",
            download_type_id: 3,
            photo: "-",
            path: "iVMS-4200.zip",
            admin: "ผู้ดูแลระบบ",
            created: "2015-09-04T23:08:24.000Z",
            dt_name: "โปรแกรม CCTV"
        },
        {
            id: 21,
            name: "โปรแกรม CMS 2000 เพื่อดูกล้อง AHD สำหรับ windows ",
            detail: "โปรแกรม/SoftWare Installation",
            description: "โปรแกรม CMS 2000 เพื่อดูกล้อง AHD สำหรับ windows การเชื่อมต่อสามารถเชื่อมได้ทั้ง DDNS และ P2P ได้เลย โดยไม่ต้อง Forward Port ให้ยุ่งยาก",
            download_type_id: 3,
            photo: "-",
            path: "CMS2000_yunyis.rar",
            admin: "ผุ้ดูแลระบบ",
            created: "2015-09-03T19:13:03.000Z",
            dt_name: "โปรแกรม CCTV"
        },
        {
            id: 20,
            name: "คู่มือการใช้งานโปรแกรม vMeyeSuper สำหรับเครื่อง Mac for Sinovision DVR",
            detail: "คู่มือการใช้งาน/UserManuals",
            description: "เอกสารประกอบการใช้งานโปรแกรม vMeyeSuper Desktop สำหรับเครื่อง iMac, MacBook, MacBook Pro, MacMini เพื่อดู CCTV ของเรา",
            download_type_id: 1,
            photo: "-",
            path: "vMeyeSuper_Mac_UserManual.pdf",
            admin: "ผู้ดูแลระบบ",
            created: "2015-08-30T19:24:11.000Z",
            dt_name: "คู่มือการใช้งาน CCTV"
        },
        {
            id: 19,
            name: "คู่มือการใช้งานโปรแกรม PSSMini Desktop สำหรับเครื่อง Mac for Dahua DVR",
            detail: "คู่มือการใช้งาน/UserManuals",
            description: "เอกสารประกอบการใช้งานโปรแกรม PSSMini สำหรับ iMac, MacBook Pro, MacBook Air,MacMini เพื่อดู CCTV ของเราผ่านระบบ Osx",
            download_type_id: 1,
            photo: "-",
            path: "PssMini_Usermanual.pdf",
            admin: "ผู้ดูแลระบบ",
            created: "2015-08-30T18:12:24.000Z",
            dt_name: "คู่มือการใช้งาน CCTV"
        },
        {
            id: 18,
            name: "คู่มือการใช้งาน iVMS-4200 Desktop สำหรับเครื่อง MacOsx For CMP7508 DVR or HikVision",
            detail: "คู่มือการใช้งาน/UserManuals",
            description: "เอกสารประกอบการใช้งาน iVMS-4200 Desktop สำหรับเครื่อง MacOsx เช่น iMac, MacAir, MacBook, MacBook Pro, MacMini",
            download_type_id: 1,
            photo: "-",
            path: "iVMS-4200_MacOsx_Usermanual.pdf",
            admin: "ผู้ดูแลระบบ",
            created: "2015-08-30T18:11:05.000Z",
            dt_name: "คู่มือการใช้งาน CCTV"
        },
        {
            id: 17,
            name: "คู่มือการใช้งานโปรแกรม CMS2000 สำหรับกล้อง AHD Camera ",
            detail: "คู่มือการใช้งาน/UserManuals",
            description: "คู่มือการใช้งานโปรแกรม CMS2000 สำหรับกล้อง AHD Camera ",
            download_type_id: 1,
            photo: "-",
            path: "CMS2000_Usermanual.pdf",
            admin: "ผู้ดูแลระบบ",
            created: "2015-08-30T21:07:22.000Z",
            dt_name: "คู่มือการใช้งาน CCTV"
        },
        {
            id: 16,
            name: "คู่มือการใช้งาน iVMS4500 สำหรับ Android",
            detail: "คู่มือการใช้งาน/UserManuals",
            description: "เอกสารประกบอการใช้งาน APP iVMS4500 สำหรับระบบ Android",
            download_type_id: 1,
            photo: "-",
            path: "iVMS4500_Android.pdf",
            admin: "ผู้ดูแลระบบ",
            created: "2015-08-30T18:05:13.000Z",
            dt_name: "คู่มือการใช้งาน CCTV"
        },
        {
            id: 15,
            name: "คู่มือการใช้งาน APP iVMS4500 Lite สำหรับ iOS Iphone,Ipad",
            detail: "คู่มือการใช้งาน/UserManuals",
            description: "เอกสารประกอบการใช้งาน APP iVMS4500 สำหรับระบบปฏิบัติการ iOS Iphone, Ipad",
            download_type_id: 1,
            photo: "-",
            path: "iVMS4500_Lite_Usermanual.pdf",
            admin: "ผู้ดูแลระบบ",
            created: "2015-08-30T19:17:07.000Z",
            dt_name: "คู่มือการใช้งาน CCTV"
        },
        {
            id: 14,
            name: "คู่มือการใช้งานโปรแกรม iVMS4200 Desktop สำหรับ DVR CMP7508 รองรับระบบ Microsoft Windows",
            detail: "คู่มือการใช้งาน/UserManuals",
            description: "เอกสารประกอบการใช้งาน โปรแกรม iVMS4200 Desktop สำหรับ DVR CMP7508 รองรับระบบปฏิบัติการ Microsoft Windows",
            download_type_id: 1,
            photo: "-",
            path: "iVMS4200_Software_Usermanual.pdf",
            admin: "ผู้ดูแลระบบ",
            created: "2015-08-30T18:02:06.000Z",
            dt_name: "คู่มือการใช้งาน CCTV"
        },
        {
            id: 13,
            name: "คู่มือการใช้งานโปรแกรม iVMS-4000 Desktop สำหรับ DVR CMPH7508 ในระบบ Windows",
            detail: "คู่มือการใช้งาน/UserManuals",
            description: "เอกสารประกอบการใช้งาน โปรแกรม iVMS-4000 Desktop สำหรับ DVR CMP7508 รองรับระบบปฏิบัติการ Microsoft Windows",
            download_type_id: 1,
            photo: "-",
            path: "iVMS4000_Software_Usermanual.pdf",
            admin: "ผู้ดูแลระบบ",
            created: "2015-08-30T18:04:17.000Z",
            dt_name: "คู่มือการใช้งาน CCTV"
        },
        {
            id: 12,
            name: "คู่มือการใช้งาน CMS สำหรับ Windows",
            detail: "คู่มือการใช้งาน/UserManuals",
            description: "เอกสารประกอบ การใช้งาน CMS Software สำหรับ Microsoft Windows",
            download_type_id: 1,
            photo: "-",
            path: "CMS_Software_Usermanual.pdf",
            admin: "ผู้ดูแลระบบ",
            created: "2015-08-30T23:29:05.000Z",
            dt_name: "คู่มือการใช้งาน CCTV"
        },
        {
            id: 11,
            name: "คู่มือการใช้งาน Host Free Dahua Technology สำหรับ Dahua DVR",
            detail: "คู่มือการใช้งาน/UserManuals",
            description: "เอกสารประกอบการใช้งาน Free Host ของ DahauDDNS เพื่อใช้งานกล้อง CCTV Dahua DVR",
            download_type_id: 1,
            photo: "-",
            path: "DahuaDDNS_Usermanual.pdf",
            admin: "ผู้ดูแลระบบ",
            created: "2015-08-30T18:14:27.000Z",
            dt_name: "คู่มือการใช้งาน CCTV"
        },
        {
            id: 10,
            name: "การใช้งาน gDMSS สำหรับ Android ใน Dahua DVR",
            detail: "คู่มือการใช้งาน/UserManuals",
            description: "เอกสารประกอบการใช้งาน APP gDMSS สำหรับระบบปฏิบัติการ Android, Ipad ใน Dahua DVR",
            download_type_id: 1,
            photo: "-",
            path: "gDMSS_Usermanual.pdf",
            admin: "ผู้ดูแลระบบ",
            created: "2015-08-30T18:10:04.000Z",
            dt_name: "คู่มือการใช้งาน CCTV"
        },
        {
            id: 9,
            name: "คู่มือการใช้งาน iDMSS Lite สำหรับ iOS ใน Dahua DVR",
            detail: "คู่มือการใช้งาน/UserManuals",
            description: "เอกสารประกอบการใช้งาน APP iDMSS สำหรับระบบปฏิบัติการ iOS Iphone, Ipad ใน Dahua DVR",
            download_type_id: 1,
            photo: "-",
            path: "iDMSS_Usermanual.pdf",
            admin: "ผู้ดูแลระบบ",
            created: "2015-08-30T20:02:13.000Z",
            dt_name: "คู่มือการใช้งาน CCTV"
        },
        {
            id: 8,
            name: "คู่มือการลงทะเบียนและใช้งาน Free DDNS ของ HiDDNS",
            detail: "คู่มือการใช้งาน/UserManuals",
            description: "คู่มือการใช้งาน DDNS  ฟรีของค่าย HiDDNS สำหรับ DVR HIP",
            download_type_id: 1,
            photo: "-",
            path: "HiDDNS_FreeHost.pdf",
            admin: "ผู้ดูแลระบบ",
            created: "2015-08-30T18:13:04.000Z",
            dt_name: "คู่มือการใช้งาน CCTV"
        },
        {
            id: 7,
            name: "คู่มือการดูกล้อง AHD Camera ผ่านหน้าเว็บ yunyis.com",
            detail: "คู่มือการใช้งาน/UserManuals",
            description: "เอกสารการดูกล้อง AHD ผ่านหน้าเว็บ yunyis.com ",
            download_type_id: 1,
            photo: "-",
            path: "View_AHD_OnLine_Yunyis.pdf",
            admin: "ผู้ดูแลระบบ",
            created: "2015-08-30T19:01:18.000Z",
            dt_name: "คู่มือการใช้งาน CCTV"
        },
        {
            id: 6,
            name: "คู่มือการใช้งาน APP N_eye สำหรับระบบ Android และ iOS",
            detail: "คู่มือการใช้งาน/UserManuals",
            description: "เอกสารประกอบการใช้งาน APP N_eye สำหรับระบบปฏิบัติการ Android, iOS สำหรับ AHD Camera",
            download_type_id: 1,
            photo: "-",
            path: "N_eye_AHD_Camera.pdf",
            admin: "ผู้ดูแลระบบ",
            created: "2015-08-30T20:28:05.000Z",
            dt_name: "คู่มือการใช้งาน CCTV"
        },
        {
            id: 5,
            name: "คู่มือการใช้งาน XMeye สำหรับ iOS, Iphone, Ipad",
            detail: "คู่มือการใช้งาน/UserManuals",
            description: "เอกสารคู่มือการใช้งาน APP XMeye สำหรับระบบ iOS Iphone,Ipad ในการเข้าดู CCTV ของท่าน",
            download_type_id: 1,
            photo: "-",
            path: "XMeye_iOS.pdf",
            admin: "ผู้ดูแลระบบ",
            created: "2015-08-30T23:27:09.000Z",
            dt_name: "คู่มือการใช้งาน CCTV"
        },
        {
            id: 4,
            name: "คู่มือการใช้งาน VMeyeClond สำหรับระบบ Android",
            detail: "คู่มือการใช้งาน/UserManuals",
            description: "คู่มือการตั้งค่าและใช้งาน APP VMeyeSuper สำหรับระบบ Android ",
            download_type_id: 1,
            photo: "-",
            path: "VMeyeClond_Android.pdf",
            admin: "ผู้ดูแลระบบ",
            created: "2015-08-30T20:11:06.000Z",
            dt_name: "คู่มือการใช้งาน CCTV"
        },
        {
            id: 3,
            name: "คู่มือการใช้งาน VMeyeSuper สำหรับระบบ Android",
            detail: "คู่มือการใช้งาน/UserManuals",
            description: "คู่มือการตั้งค่าและใช้งาน APP VMeyeSuper สำหรับระบบ Android ",
            download_type_id: 1,
            photo: "-",
            path: "VMeyeSuper_Android.pdf",
            admin: "ผู้ดูแลระบบ",
            created: "2015-08-30T20:11:06.000Z",
            dt_name: "คู่มือการใช้งาน CCTV"
        },
        {
            id: 2,
            name: "คู่มือการตั้งต่า DVR เชื่อมกับ P2P/Clond  ผ่าน xmeye.net",
            detail: "คู่มือการใช้งาน/UserManuals",
            description: "การลงทะเบียน DVR Clond Server ผ่าน http://xmeye.net เพื่อใช้งาน CCTV บนระบบ Clond Server ได้ ",
            download_type_id: 1,
            photo: "-",
            path: "AHD_DVR_Clond_Server.pdf",
            admin: "ผู้ดูแลระบบ",
            created: "2015-08-30T22:05:39.000Z",
            dt_name: "คู่มือการใช้งาน CCTV"
        },
        {
            id: 1,
            name: "คู่มือการสมัคร DDNS และการ Forwarding Port Router Cisco",
            detail: "คู่มือการใช้งาน/UserManuals",
            description: "เอกสาร คู่มือการใช้งาน การสมัคร DDNS และ การ Forwarding Port ในอุปกรณ์ Router Cisco เพื่อนำไปใช้ในการใช้งาน CCTV",
            download_type_id: 1,
            photo: "-",
            path: "Register_NO-IP_and_ForwardPort.pdf",
            admin: "ผู้ดูแลระบบ",
            created: "2015-08-30T11:07:14.000Z",
            dt_name: "คู่มือการใช้งาน CCTV"
        }
    ];
exports.findAll = () => {
    return downloads;
};